---
- name: Installing tomcat 9
  hosts: all
  become: yes
  tasks:
    - name: installing open jdk 11
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: ensure the tomcat group exist
      group:
        name: "{{ tomcat_group }}"
        state: present
    - name: ensure home directory exists
      file: 
        path: "{{ tomcat_home_dir }}"
        state: directory
    - name: Ensure the user tomcat exists
      user:
        name: "{{ tomcat_user }}" 
        group: "{{ tomcat_group }}"
        home: "{{ tomcat_home_dir }}"
        shell: "{{ tomcat_shell }}"
    - name: download tomcat
      get_url:
        url: "{{ tomcat_download_url }}"
        dest: "{{ tomcat_download_dest }}"
    - name: check if the tomcat is extracted
      stat:
        path: "{{ tomcat_check_dir }}"
      register: tomcat_conf
    - name: untar the tomcat
      command: "sudo tar xzvf {{ tomcat_download_dest }} -C {{ tomcat_home_dir }} --strip-components=1"
      when: not tomcat_conf.stat.exists




